# Copyright (c) 2021 Qualcomm Technologies, Inc.
# All Rights Reserved.

from .pretrained_bert import BertForSequenceClassification, BertForWordClassification, BertForMultiLabelClassification
from .quantized_bert import QuantizedBertForSequenceClassification, QuantizedBertForWordClassification, QuantizedBertForMultiLabelClassification, _quantize_model
from .quantized_mobilebert import QuantizedMobileBertForSequenceClassification
from .quantized_roberta import QuantizedRobertaForSequenceClassification
